- ros_topic_name: "thruster_cmd"
  gz_topic_name: "/model/my_lrauv/joint/propeller_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  subscriber_queue: 5
  publisher_queue: 5
  lazy: true
  direction: ROS_TO_GZ      # Only sending commands from ROS â†’ Gazebo

- ros_topic_name: "vertical_fin_cmd"
  gz_topic_name: "/model/my_lrauv/joint/vertical_fins_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  subscriber_queue: 5
  publisher_queue: 5
  lazy: true
  direction: ROS_TO_GZ
